### ISSUE TITLE
New Update on PYPI

### ISSUE THREAD

**Issue by Kalebu** [Kalebu/alright#137]
<samp>
Pushed upgrade on PYPI (2.6)
----------------------------

Just pushed a new update to Pypi with most of the issues fixed including but not limited to 
- find_by_username xpath
- sending_pictures xpath
- sending_videos xpath
- sending_documents xpath

Please upgrade your package to use the latest changes 

```bash
pip install ---upgrade alright
```
</samp>

**Comment by giulio333** [comment]
Hi! Just updated but but I got this error:

line 16, in validate_response      
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116.0.5845

**Comment by giulio333** [comment]
Just solved with "pip install webdriver-manager" to version 4.0.0

**Comment by alexferra** [comment]
@Kalebu cant get this to work, to start:

, line 39, in __init__
    browser = webdriver.Chrome(
TypeError: WebDriver.__init__() got multiple values for argument 'options'


I fix this issue and get it running but still doesnt work.

**Comment by alexferra** [comment]
@Kalebu 
error on get_last_message_received


alright\__init__.py", line 732, in get_last_message_received
    EC.presence_of_all_elements_located(
TypeError: presence_of_all_elements_located() takes 1 positional argument but 2 were given

**Comment by Kalebu** [comment]
> @Kalebu error on get_last_message_received
> 
> alright__init__.py", line 732, in get_last_message_received EC.presence_of_all_elements_located( TypeError: presence_of_all_elements_located() takes 1 positional argument but 2 were given
> 
> I think solution is just to include ()

Thank you for picking up this, Fixed, will be included in the next PYPI upgrade

**Comment by leggewie** [comment]
Thank you for your work on alright!

Two comments, I would like to make
- it is utterly unclear what codebase on PyPi relates to what git version or commit. can that be improved?
- please read http://semver.org (releasing version 2.61 as a bug fix to version 2.6 is not a good idea)
